version: 1.4.3-beta{build}
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: dotnet.exe restore
after_build:
- ps: >-
    $versionSuffix=(Get-Item Env:APPVEYOR_BUILD_NUMBER).Value
    
    Set-Location "nupkg"
    
    .\pack.ps1 -versionSuffix "$versionSuffix"
build:
  verbosity: minimal
test:
  assemblies:
  - test\Abp.AutoMapper.Tests\bin\Debug\net452\win7-x64\Abp.AutoMapper.dll
  - test\Abp.EntityFramework.Tests\bin\Debug\net452\win7-x64\Abp.EntityFramework.Tests.dll
  - test\Abp.MemoryDb.Tests\bin\Debug\net452\win7-x64\Abp.MemoryDb.Tests.dll
  - test\Abp.NHibernate.Tests\bin\Debug\net452\win7-x64\Abp.NHibernate.Tests.dll
  - test\Abp.TestBase.SampleApplication.Tests\bin\Debug\net452\win7-x64\Abp.TestBase.SampleApplication.Tests.dll
  - test\Abp.TestBase.Tests\bin\Debug\net452\win7-x64\Abp.TestBase.Tests.dll
  - test\Abp.Tests\bin\Debug\net452\win7-x64\Abp.Tests.dll
  - test\Abp.Web.Api.Tests\bin\Debug\net452\win7-x64\Abp.Web.Api.Tests.dll
  - test\Abp.Web.Mvc.Tests\bin\Debug\net452\win7-x64\Abp.Web.Mvc.Tests.dll
  - test\Abp.Web.Tests\bin\Debug\net452\win7-x64\Abp.Web.Tests.dll
  - test\Abp.EntityFrameworkCore.Tests\bin\Debug\net461\win7-x64\Abp.EntityFrameworkCore.Tests.dll
  - test\Abp.AspNetCore.Tests\bin\Debug\net461\win7-x64\Abp.AspNetCore.Tests.dll
  - test\Abp.EntityFramework.GraphDiff.Tests\bin\Debug\net452\win7-x64\Abp.EntityFramework.GraphDiff.Tests.dll
  - test\Abp.Dapper.Tests\bin\Debug\net461\win7-x64\Abp.Dapper.Tests.dll
  - test\Abp.Quartz.Tests\bin\Debug\net461\win7-x64\Abp.Quartz.Tests.dll
  - test\Abp.Web.Common.Tests\bin\Debug\net461\win7-x64\Abp.Web.Common.Tests.dll
artifacts:
- path: nupkg\*.nupkg
  name: nuget-packages